server:
  port: ${PORT:8080}
  compression:
      enabled: true
      min-response-size: 1
app:
  token:
    private-key: ${JWT_PRIVATE_KEY:MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCZP+H+KPyNO3xRs2Q7lfE73gwtMsehyx8OZf9yAxVqje7ywp6sU3VDpxdjY+UuPFnR/BqZ0sONcVLDPpPUaD45kmWKBgKjdYVcRD8xitmF0R0Ed2toMyob01JxLUOT+Hw393hXxqgzflrobsMhigh2gE//3cJKvTEH5WAVlzkc5xVtGiqE64psIXfU5aszguCyUgF2R4QpWP3QXQOJ/wDWAVSqSyL6cB5SkhdfEvGtQgKqspXFrtveI/9L6TR+35kP9+CjD3+aeIFZVH053a1EAuCIE6r77wW9C2CALDCqUw33Ld40DbQ2KzKyTH70V/sbebkqApunv22fKeXs0iDJAgMBAAECggEABhaDGFExgzzPOgGp5DIXNL0j97GyO4uxrqU/qhxUP/jmeq9flVH1cRwUskaYJqeQG+breZvlV9ueIZJ9Ve1UN35I2VxWw36aLymo5wNwk7/UasaBtlB+Bj/1YPie3CR9bs2+cqI6MV1+KAiqaM0ue+KqCuyY2NY+OeWTVRg+VRcLRnSlQv7YGnTqWtXGaIfYIRGHw6ldJnaov3PVsVtbJpAzrFAgJouKcKABC2rqmYcVYSzPwE/BAYR6XzVF4py42efm0hyJTzojwwV7Otw1DR2NGVX3uNeuSipsbr954v7RPKNSpPD6tKqAZGzvC05k2H/9+dK/m+izAbKuZJ8GuQKBgQDH9jTNho2h0pIbajHX8ricFfVOa8O5OB3pdQbF1H/I+EKV1ba2DFfO7sVuFwfVqVBMsU2u5oszp2eUEZIXx1znYsc0LkY3CWR4c2XNekLneSS0jQIOofX5nUSuLhdoewdQP7vtmuaNqmOwogCbqY3kppdHeapHBkCEf2/nbEvkjQKBgQDEMmrfdmqVValvz+toC1LISDnPGF3bLwAPrNf43BYahdpzdamrDqwZr5FNjEmlJBRuHos1U4LoJnbQC9D7ZQB17dETTqYKTGZ8H8Zx9tKVSNFFBEGKYDnufjNKnZthoVZvpcoD2ESihlnQ7kqpZt5UHpFGlvQ895oOy0rfjDvELQKBgG88JgmC5Tz073QysgGIM2wYxvpV9m4Nqo4ZHKhmWqOIfznsxhQlb59cshVY2HHiGxpes3EtLJiScosq7xMtQyAwkdIUP9kT74EV6LbSYW90s5eArXlIXZX7B57BYyIq9lmM6tT1i3WZKJW0uRPe0WE1zwfixXd3IeLTJYQeeWVtAoGASskBDd7gb73wUQuLKuSuEGPfjT43gHXg6xiyVkzmLAP7qeke3HJCTaQrmciwxb8D/pmr7I7BpmYLAfCPH1R3oXweJuLizagjpIqkJQq1aGwSQOGHbgyR6IO4X2fGM6fA/9vNLjwApYbas5YxZXMtqhjgvWyK+rZSxfLdvmqA2Z0CgYBGjqsVkSypDIoLW3Ek5jqYurtlCvpgJm8tFs+STNjfpxle2C+w3A/tWXjRSs7UdJu/yKbz3bjZhLK3NC5OHb01ifWRxU2FDs+/74aWqNZfKIQuasfVI0aYX5wRUCGgrLqVPpyQWm7+qiai+mb1V0P3TNaR+SX5MMpHRMTfH5hMfg==}
    public-key: ${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmT/h/ij8jTt8UbNkO5XxO94MLTLHocsfDmX/cgMVao3u8sKerFN1Q6cXY2PlLjxZ0fwamdLDjXFSwz6T1Gg+OZJligYCo3WFXEQ/MYrZhdEdBHdraDMqG9NScS1Dk/h8N/d4V8aoM35a6G7DIYoIdoBP/93CSr0xB+VgFZc5HOcVbRoqhOuKbCF31OWrM4LgslIBdkeEKVj90F0Dif8A1gFUqksi+nAeUpIXXxLxrUICqrKVxa7b3iP/S+k0ft+ZD/fgow9/mniBWVR9Od2tRALgiBOq++8FvQtggCwwqlMN9y3eNA20Nisyskx+9Ff7G3m5KgKbp79tnynl7NIgyQIDAQAB}
spring:
  profiles:
    active: prod
  main:
    allow-circular-references: true
  application:
    name: stateless-auth-api
  devtools:
    add-properties: true
  security:
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:@db.host@}:${DB_PORT:@db.port@}/${DB_NAME:@db.name@}
    username: ${DB_USER:@db.user@}
    password: ${DB_PASSWORD:@db.pass@}
    initialization-mode: always
    initialize: true
    defer-datasource-initialization: false
    continue-on-error: true
    maxActive: 3
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    generate-ddl: true
    show_sql: true
    open-in-view: false
    globally_quoted_identifiers: true
    globally_quoted_identifiers_skip_column_definitions: true
redis:
  host: ${REDIS_HOST:@redis.host@}
  port: ${REDIS_PORT:@redis.port@}