server:
  port: ${PORT:8080}
  compression:
      enabled: true
      min-response-size: 1
app:
  token:
    secret-key: ${JWT_SECRET_KEY:Y3Vyc28tYXV0ZW50aWNhY2FvLXN0YXRlZnVsLXN0YXRlbGVzcy1taWNyb3NzZXJ2aWNvcw==}
spring:
  profiles:
    active: prod
  main:
    allow-circular-references: true
  application:
    name: stateless-auth-api
  devtools:
    add-properties: true
  security:
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:@db.host@}:${DB_PORT:@db.port@}/${DB_NAME:@db.name@}
    username: ${DB_USER:@db.user@}
    password: ${DB_PASSWORD:@db.pass@}
    initialization-mode: always
    initialize: true
    defer-datasource-initialization: false
    continue-on-error: true
    maxActive: 3
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    generate-ddl: true
    show_sql: true
    open-in-view: false
    globally_quoted_identifiers: true
    globally_quoted_identifiers_skip_column_definitions: true
redis:
  host: ${REDIS_HOST:@redis.host@}
  port: ${REDIS_PORT:@redis.port@}