services:
  
  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - auth
    ports:
      - "5432:5432"
    volumes:
      - "pgsqlconfStateless:/etc/postgresql"
      - "pgsqldataStateless:/var/lib/postgresql/data"
      - "pgsqldblogsStateless:/var/log"
  
  stateful-auth-db:
    container_name: stateful-auth-db
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - auth
    ports:
      - "5433:5432"
    volumes:
      - "pgsqlconfStateful:/etc/postgresql"
      - "pgsqldataStateful:/var/lib/postgresql/data"
      - "pgsqldblogsStateful:/var/log"

  token-redis:
    container_name: token-redis
    image: redis:7.2.4-alpine
    networks:
      - auth
    ports:
      - "6379:6379"
    volumes:
      - "redisToken:/data"

volumes:
  pgsqlconfStateless:
  pgsqldataStateless:
  pgsqldblogsStateless:
  pgsqlconfStateful:
  pgsqldataStateful:
  pgsqldblogsStateful:
  redisToken:

networks:
  auth:
    driver: bridge
