---
server:
  port: ${PORT:8081}
  compression:
    enabled: true
    min-response-size: 1
spring:
  application:
    name: stateless-any-api
  profiles:
    active: prod
  devtools:
    add-properties: true
app:
  token:
    public-key: ${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmT/h/ij8jTt8UbNkO5XxO94MLTLHocsfDmX/cgMVao3u8sKerFN1Q6cXY2PlLjxZ0fwamdLDjXFSwz6T1Gg+OZJligYCo3WFXEQ/MYrZhdEdBHdraDMqG9NScS1Dk/h8N/d4V8aoM35a6G7DIYoIdoBP/93CSr0xB+VgFZc5HOcVbRoqhOuKbCF31OWrM4LgslIBdkeEKVj90F0Dif8A1gFUqksi+nAeUpIXXxLxrUICqrKVxa7b3iP/S+k0ft+ZD/fgow9/mniBWVR9Od2tRALgiBOq++8FvQtggCwwqlMN9y3eNA20Nisyskx+9Ff7G3m5KgKbp79tnynl7NIgyQIDAQAB}