# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Validação e Build do projeto

on:
  push:
    branches: [ "main", "release/**" ]
    tags:        
    - v*
    paths-ignore:
    - '**.md'
    - '**.sh'
    - '**.json'
  pull_request:
    branches: [ "main", "release/**" ]
    tags:        
    - v*
    paths-ignore:
    - '**.md'
    - '**.sh'
    - '**.json'

jobs:
  checkstyle-stateful-any-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando checkstyle
      run: mvn checkstyle:check -pl stateful/stateful-any-api -Dmaven.test.skip=true

  pmd-stateful-any-api:
    needs: ["checkstyle-stateful-any-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando PMD
      run: mvn pmd:check -pl stateful/stateful-any-api -Dmaven.test.skip=true

  spotbugs-stateful-any-api:
    needs: ["pmd-stateful-any-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando spotbugs
      run: mvn spotbugs:check -pl stateful/stateful-any-api -Dmaven.test.skip=true

  test-stateful-any-api:
    needs: ["spotbugs-stateful-any-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Teste do projeto
      run: mvn -B test -pl stateful/stateful-any-api

  build-stateful-any-api:
    needs: ["test-stateful-any-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build do projeto
      run: mvn -B package -pl stateful/stateful-any-api -Dmaven.test.skip=true

# ---------------------------------------

  checkstyle-stateful-auth-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando checkstyle
      run: mvn checkstyle:check -pl stateful/stateful-auth-api -Dmaven.test.skip=true

  pmd-stateful-auth-api:
    needs: ["checkstyle-stateful-auth-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando PMD
      run: mvn pmd:check -pl stateful/stateful-auth-api -Dmaven.test.skip=true

  spotbugs-stateful-auth-api:
    needs: ["pmd-stateful-auth-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando spotbugs
      run: mvn spotbugs:check -pl stateful/stateful-auth-api -Dmaven.test.skip=true

  test-stateful-auth-api:
    needs: ["spotbugs-stateful-auth-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Teste do projeto
      run: mvn -B test -pl stateful/stateful-auth-api

  build-stateful-auth-api:
    needs: ["test-stateful-auth-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build do projeto
      run: mvn -B package -pl stateful/stateful-auth-api -Dmaven.test.skip=true

# ---------------------------------------

  checkstyle-stateless-any-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando checkstyle
      run: mvn checkstyle:check -pl stateless/stateless-any-api -Dmaven.test.skip=true

  pmd-stateless-any-api:
    needs: ["checkstyle-stateless-any-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando PMD
      run: mvn pmd:check -pl stateless/stateless-any-api -Dmaven.test.skip=true

  spotbugs-stateless-any-api:
    needs: ["pmd-stateless-any-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando spotbugs
      run: mvn spotbugs:check -pl stateless/stateless-any-api -Dmaven.test.skip=true

  test-stateless-any-api:
    needs: ["spotbugs-stateless-any-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Teste do projeto
      run: mvn -B test -pl stateless/stateless-any-api

  build-stateless-any-api:
    needs: ["test-stateless-any-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build do projeto
      run: mvn -B package -pl stateless/stateless-any-api -Dmaven.test.skip=true

# ---------------------------------------

  checkstyle-stateless-auth-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando checkstyle
      run: mvn checkstyle:check -pl stateless/stateless-auth-api -Dmaven.test.skip=true

  pmd-stateless-auth-api:
    needs: ["checkstyle-stateless-auth-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando PMD
      run: mvn pmd:check -pl stateless/stateless-auth-api -Dmaven.test.skip=true

  spotbugs-stateless-auth-api:
    needs: ["pmd-stateless-auth-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verificando spotbugs
      run: mvn spotbugs:check -pl stateless/stateless-auth-api -Dmaven.test.skip=true

  test-stateless-auth-api:
    needs: ["spotbugs-stateless-auth-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Teste do projeto
      run: mvn -B test -pl stateless/stateless-auth-api

  build-stateless-auth-api:
    needs: ["test-stateless-auth-api"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build do projeto
      run: mvn -B package -pl stateless/stateless-auth-api -Dmaven.test.skip=true